### ISSUE TITLE
Set a default timezone and language and country  of each account from install OS setting value.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-rs#50]

**Comment by stmtstk** [comment]
@ta-hiroki 

I moved this issue to stip-rs repository.

I checked the source code of  `locale.getlocale()'.
It seems that `locale.getlocale()` try to locale value from environment values.
So when you execute this on a python interpreter, this function works well.
However, on apache2 (with www-data user), it seems that these environment value are not set.
We should search other ways to get language settings.

---

issue は動かしました。
`locale.getlocale()` は環境変数を見て返却をしているように思えます。
ですので、python interpreter では @ta-hiroki  user の bash かなにかの LANG 環境変数を見ています。
一方、apchce2 は www-data ですので、環境変数が設定していないように見受けられます。
別の方法の検索も検討に入れてもらえませんか？

**Comment by ta-hiroki** [comment]
@stmtstk 

I also checked the environment variables for the www-data user.
However, it was different from the environment variable data available in S-TIP's src.
It seems that the processing in settings.py also affects.

I am investigating other ways to get it.
It will take some time.

In addition, I have one question. 
Do I need to consider Windows OS?

---

www-data ユーザの環境変数も確認しました。
しかし、S-TIP の src で取得できる環境変数のデータと異なりました。
settings.py での処理も影響していそうです。

別の取得方法も含めて調査中ですが、
少し時間がかかりそうです。

加えて1点質問があります。
Windows OS の場合の考慮は必要でしょうか?

**Comment by stmtstk** [comment]
@ta-hiroki 

It is OK to take the time to investigate. Take it easy.
We should it works well regardeless of OS, but we should resolve about Ubuntu OS.

---

調査はじっくり時間をかけていきましょう。問題ないと思います。
OS 問わずの動作が望ましいですが、まずは Ubuntu で動作することに注力しましょう。

**Comment by ta-hiroki** [comment]
@stmtstk 

I can use the python subprocess module to get the result of a command that checks locale and timezone information. (Only works with Ubuntu)
> $ timezone = subprocess.run(['cat', '/etc/timezone'], encoding='utf-8', stdout=subprocess.PIPE)  
$ timezone.stdout
→ 'Etc/UTC\n'

> $ locale = subprocess.run(['cat', '/etc/default/locale'], encoding='utf-8', stdout=subprocess.PIPE)
$ locale.stdout
→ 'LANG=ja_JP.UTF-8\\nLANGUAGE=ja_JP:ja\\n'

The process of obtaining necessary information from the obtained data is assumed as follows.
- timezone removes and uses `\n`.
- locale is separated by `\n`. Check each one and use the information after `LANG=`.

How about this method?

---

python の subprocess モジュールを利用して locale, timezone 情報を確認するコマンド結果を取得できます。(Ubuntu でのみ機能)   
取得後のデータから必要となる情報を取得する処理は以下を想定しています。
- timezone は `\n` を削除して利用。
- locale は `\n` で区切り list にし、list を1つずつ確認し `LANG=` 以降の情報を利用。

この方法はどうでしょうか?

**Comment by stmtstk** [comment]
@ta-hiroki 

Thank you for your investigataion.

I understand that we can get a local information from system files.
We should get the information from read files instead of using a `subprocess` command.

If S-TIP run on Ubuntu (Linux), get the local information from system files,
if S-TIP did not run on Ubuntu (i.e. Windows), S-TIP use default settings (Language English, Country USA, Timezone UTC).

https://qiita.com/toyolab/items/c8b54b95e61d4218f869

We can get OS System Name from `os.name`.

---

Ubuntu のみであるが、システムファイルから取得できることは理解しました。
であれば、`subprocess`  を使わなくても単なる file open で実現しましょう。

`os.name` で Linux かどうかが判断できるので、 Linux であれば、上記システムファイルから取得、
それ以外 (Windows とか) だったり、ファイルが開けなかったり、取得ができなかった場合は、
デフォルト設定で進める。

というのはいかがでしょうか?

**Comment by ta-hiroki** [comment]
@stmtstk 

All right. 
Implemented using open ().

---

承知いたしました。
python の open() を利用した方法で実装致します。
